[package]
name = "learning_rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.75"
license = "MIT"

[lints.rust]
unsafe_code = "forbid"
unused = "allow"       # For exploratory dev.

[dependencies]
lazy_static = "1.4.0"
